# Análisis de datos: data_cobre_c2.csv
Este notebook carga y explora los datos químicos y de intensidad de la planta de cobre contenidos en `data_cobre_c2.csv` para posteriormente cargarlos a la base de datos.

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración de estilo de gráficos
plt.style.use('ggplot')
sns.set_palette('Set2')

In [37]:
# Ruta del archivo CSV
file_path = 'data/raw/data_cobre_c2.csv'

# Cargar los datos
# - thousands=',': para interpretar los números con separadores de miles
# - na_values: para reconocer valores faltantes específicos de este archivo
df = pd.read_csv(file_path, thousands=',', na_values=['-', ' -   ', '#DIV/0!', ' '])

# Limpieza de nombres de columnas
# Reemplazar saltos de línea (como en "PESO\n TOTAL") y limpiar comillas y espacios en blanco adicionales
df.columns = df.columns.str.replace('\n', ' ').str.strip()
df.columns = [col.replace('"', '').strip() for col in df.columns]

# Eliminar columnas que estén completamente vacías (ej: primera y última columna)
df = df.dropna(axis=1, how='all')

# Ver información básica del DataFrame resultante
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4328 entries, 0 to 4327
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fecha            2638 non-null   str
 1   Hora             2623 non-null   str
 2   Tara             2622 non-null   float64
 3   PESOTOTAL        2622 non-null   float64
 4   PESO SECO        2622 non-null   float64
 5   PESO PULPA       2622 non-null   float64
 6   Cod lab Quimico  2550 non-null   float64
 7   MUESTRA          2607 non-null   str
 8   %Fe              2605 non-null   float64
 9   %Cu              2605 non-null   float64
 10  %Zn              2513 non-null   float64
 11  %Mo              2605 non-null   float64
 12  %Ins             2450 non-null   float64
 13  %Sol             2627 non-null   float64
dtypes: float64(11), str(3)
memory usage: 473.5 KB

In [38]:
# Mostrar las primeras filas
df.head()

,Fecha,Hora,Tara,PESOTOTAL,PESO SECO,PESO PULPA,Cod lab Quimico,MUESTRA,%Fe,%Cu,%Zn,%Mo,%Ins,%Sol
0,2022/12/05,15:27,109.5,1255.0,433.0,1145.5,4845.0,Rebose Hidrociclones L1,2752.000,0.512,0.005,0.020,NaN,37.80
1,2022/12/05,15:23,109.0,1177.5,310.5,1068.5,4846.0,Relave Final,2.394,0.058,0.000,0.005,0.00,29.06
2,2022/12/05,15:38,110.0,1027.0,234.5,917.0,4847.0,Concentrado Colectivo,31.310,22.190,0.111,0.930,10.56,25.57
3,2022/12/05,15:25,110.0,1205.5,325.5,1095.5,4848.0,Concentrado Primario L1,25.650,12.440,0.067,0.545,29.90,29.71
4,2022/12/07,12:04,109.5,1230.0,415.5,1120.5,4851.0,Rebose Hidrociclones L1,2596.000,0.481,0.004,0.017,NaN,37.08

In [39]:
# Estadísticas descriptivas de las variables numéricas
df.describe()

,Tara,PESOTOTAL,PESO SECO,PESO PULPA,Cod lab Quimico,%Fe,%Cu,%Zn,%Mo,%Ins,%Sol
count,2622.000000,2622.000000,2622.000000,2622.000000,2.550000e+03,2605.000000,2605.000000,2513.000000,2605.000000,2450.000000,2627.000000
mean,109.958085,995.055988,215.209268,885.097941,9.127085e+08,418.901813,297.810334,2.203458,36.464258,82.171902,24.798135
std,2.496450,437.034748,122.408126,437.172970,9.277961e+08,3074.149211,2490.926202,61.964713,277.737536,1334.895500,13.768665
min,11.500000,174.500000,4.500000,60.000000,4.845000e+03,0.555000,0.010000,0.000000,0.000000,0.000000,0.680000
25%,109.000000,849.625000,117.500000,740.000000,5.817750e+03,3.219000,0.274000,0.000000,0.015000,0.000000,13.955000
50%,110.000000,977.000000,200.000000,867.750000,1.713198e+09,20.800000,11.101000,0.005000,0.438000,8.240000,24.380000
75%,110.500000,1101.375000,298.000000,991.375000,1.738942e+09,27.250000,21.113000,0.108000,1.151000,18.855000,34.890000
max,140.000000,13334.000000,1121.500000,13225.000000,1.750009e+10,30671.000000,29452.000000,1884.000000,6404.000000,38180.000000,295.000000

In [40]:
# Convertir la columna Fecha a datetime, manejando el formato mixto del CSV (e.g. 2022/12/05 y 19-Dec-22)
#df['Fecha'] = pd.to_datetime(df['Fecha'], errors='coerce', format='mixed', dayfirst=True)

# Visualizar la cantidad de registros por cada tipo de muestra
df['MUESTRA'].value_counts()

MUESTRA
C2CP - Cobre - 05 Cola Scavenger L2              205
C2CP - Cobre - 04 Cola Scavenger L1              204
C2CP - Cobre - 03 Relave Final                   202
C2CP - Cobre - 07 Concentrado 1ra Limpieza L1    192
C2CP - Cobre - 09 Concentrado Colectivo          191
C2CP - Cobre - 08 Concentrado 1ra Limpieza L2    183
C2CP - Cobre - 10 Concentrado Primario L2        167
C2CP - Cobre - 11 Concentrado Primario L1        163
C2CP - Cobre - 02 Rebose Hidrociclones L2        161
C2CP - Cobre - 01 Rebose Hidrociclones L1        119
Relave Final                                     113
Concentrado Colectivo                             90
Rebose Hidrociclones L1                           84
Concentrado Primario L2                           80
Rebose Hidrociclones L2                           69
Concentrado Primario L1                           60
Cola Scavenger L2                                 48
Cola Scavenger L1                                 40
Conc, Colectivo                                   28
C2CP - Cobre - 10 Concentrado Colectivo           28
Conc, 1era Limp, L1                               27
C2CP - Cobre - 08 Concentrado 1ra Limpieza L1     25
C2CP - Cobre - 15 Concentrado Primario L1         24
Conc, Primario L2                                 22
C2CP - Cobre - 09 Concentrado 1ra Limpieza L2     20
C2CP - Cobre - 14 Concentrado Primario L2         19
Conc, Primario L1                                 11
Conc, 1era Limp, L2                                9
Rebose HidroCi, L1                                 6
Rebose Hidrociclone L2                             5
Rebose Hidrociclone L1                             5
Relave Final                                       3
C2CP - Cobre - 10 Concentrado Primario L1          3
C2CP - Cobre - 07 Concentrado 1ra Limpieza L2      1
Name: count, dtype: int64

In [41]:
# Diccionario para corregir los nombres de la columna MUESTRA
correcciones = {
    'C2CP - Cobre - 05 Cola Scavenger L2': 'Cola Scavenger L2',
    'C2CP - Cobre - 04 Cola Scavenger L1': 'Cola Scavenger L1',
    'C2CP - Cobre - 03 Relave Final': 'Relave Final',
    'C2CP - Cobre - 07 Concentrado 1ra Limpieza L1': 'Concentrado 1ra Limpieza L1',
    'C2CP - Cobre - 09 Concentrado Colectivo': 'Concentrado Colectivo',
    'C2CP - Cobre - 08 Concentrado 1ra Limpieza L2': 'Concentrado 1ra Limpieza L2',
    'C2CP - Cobre - 10 Concentrado Primario L2': 'Concentrado Primario L2',
    'C2CP - Cobre - 11 Concentrado Primario L1': 'Concentrado Primario L1',
    'C2CP - Cobre - 02 Rebose Hidrociclones L2': 'Rebose Hidrociclones L2',
    'C2CP - Cobre - 01 Rebose Hidrociclones L1': 'Rebose Hidrociclones L1',
    'Relave Final': 'Relave Final',
    'Concentrado Colectivo': 'Concentrado Colectivo',
    'Rebose Hidrociclones L1': 'Rebose Hidrociclones L1',
    'Concentrado Primario L2': 'Concentrado Primario L2',
    'Rebose Hidrociclones L2': 'Rebose Hidrociclones L2',
    'Concentrado Primario L1': 'Concentrado Primario L1',
    'Cola Scavenger L2': 'Cola Scavenger L2',
    'Cola Scavenger L1': 'Cola Scavenger L1',
    'Conc, Colectivo': 'Concentrado Colectivo',
    'C2CP - Cobre - 10 Concentrado Colectivo': 'Concentrado Colectivo',
    'Conc, 1era Limp, L1': 'Concentrado 1ra Limpieza L1',
    'C2CP - Cobre - 08 Concentrado 1ra Limpieza L1': 'Concentrado 1ra Limpieza L1',
    'C2CP - Cobre - 15 Concentrado Primario L1': 'Concentrado Primario L1',
    'Conc, Primario L2': 'Concentrado Primario L2',
    'C2CP - Cobre - 09 Concentrado 1ra Limpieza L2': 'Concentrado 1ra Limpieza L2',
    'C2CP - Cobre - 14 Concentrado Primario L2': 'Concentrado Primario L2',
    'Conc, Primario L1': 'Concentrado Primario L1',
    'Conc, 1era Limp, L2': 'Concentrado 1ra Limpieza L2',
    'Rebose HidroCi, L1': 'Rebose Hidrociclones L1',
    'Rebose Hidrociclone L2': 'Rebose Hidrociclones L2',
    'Rebose Hidrociclone L1': 'Rebose Hidrociclones L1',
    'C2CP - Cobre - 10 Concentrado Primario L1': 'Concentrado Primario L1',
    'C2CP - Cobre - 07 Concentrado 1ra Limpieza L2': 'Concentrado 1ra Limpieza L2'
}

# Aplicar el mapeo para homogeneizar los nombres
df['MUESTRA'] = df['MUESTRA'].str.strip().map(correcciones).fillna(df['MUESTRA'])

# Asignar los códigos según la lista proporcionada
mapeo_codigos = {
    'Concentrado Primario L1': 'C_01_S15',
    'Concentrado Primario L2': 'C_01_S14',
    'Concentrado Colectivo': 'C_01_S10',
    'Concentrado 1ra Limpieza L2': 'C_01_S09',
    'Concentrado 1ra Limpieza L1': 'C_01_S08',
    'Cola Scavenger L2': 'C_01_S05',
    'Cola Scavenger L1': 'C_01_S04',
    'Relave Final': 'C_01_S03',
    'Rebose Hidrociclones L2': 'C_01_S02',
    'Rebose Hidrociclones L1': 'C_01_S01'
}
df['CODIGO_MUESTRA'] = df['MUESTRA'].map(mapeo_codigos)

# Verificar los resultados limpios
df['MUESTRA'].value_counts()

MUESTRA
Concentrado Colectivo          337
Relave Final                   318
Concentrado Primario L2        288
Concentrado Primario L1        261
Cola Scavenger L2              253
Cola Scavenger L1              244
Concentrado 1ra Limpieza L1    244
Rebose Hidrociclones L2        235
Rebose Hidrociclones L1        214
Concentrado 1ra Limpieza L2    213
Name: count, dtype: int64

In [44]:
# Mapeo de columnas del DataFrame original a los campos del modelo Django 'Assay'
column_mapping = {
    'Fecha': 'date',
    'Hora': 'time',
    'Tara': 'tara',
    'PESOTOTAL': 'tweight',
    'PESO SECO': 'dweight',
    'PESO PULPA': 'pweight',
    'Cod lab Quimico': 'chemical_id',
    '% Fe': 'pFe',
    '% Cu': 'pCu',
    '% Zn': 'pZn',
    '% Mo': 'pMo',
    '% Ins': 'pIns',
    '%Sol': 'pSol'
}

# Preparar el dataframe final renombrando columnas
df_final = df.rename(columns=column_mapping).copy()

# Eliminar filas que no tengan un valor válido de Muestra (e.g. nulos) o de Cu
#df_final = df_final.dropna(subset=['pCu', 'CODIGO_MUESTRA'])

# Seleccionar solo las columnas que corresponden al modelo (más CODIGO_MUESTRA)
#model_fields = list(column_mapping.values()) + ['CODIGO_MUESTRA']
#df_final = df_final[[col for col in model_fields if col in df_final.columns]]

df_final.head()

,date,time,tara,tweight,dweight,pweight,chemical_id,MUESTRA,%Fe,%Cu,%Zn,%Mo,%Ins,pSol,CODIGO_MUESTRA
0,2022/12/05,15:27,109.5,1255.0,433.0,1145.5,4845.0,Rebose Hidrociclones L1,2752.000,0.512,0.005,0.020,NaN,37.80,C_01_S01
1,2022/12/05,15:23,109.0,1177.5,310.5,1068.5,4846.0,Relave Final,2.394,0.058,0.000,0.005,0.00,29.06,C_01_S03
2,2022/12/05,15:38,110.0,1027.0,234.5,917.0,4847.0,Concentrado Colectivo,31.310,22.190,0.111,0.930,10.56,25.57,C_01_S10
3,2022/12/05,15:25,110.0,1205.5,325.5,1095.5,4848.0,Concentrado Primario L1,25.650,12.440,0.067,0.545,29.90,29.71,C_01_S15
4,2022/12/07,12:04,109.5,1230.0,415.5,1120.5,4851.0,Rebose Hidrociclones L1,2596.000,0.481,0.004,0.017,NaN,37.08,C_01_S01

In [45]:
df_final.to_csv('data/processed/data_cobre_c2v1.csv', index=False)

In [46]:
# Ruta del archivo CSV
file_path = 'data/processed/data_cobre_c2v1.csv'

# Cargar los datos
# - thousands=',': para interpretar los números con separadores de miles
# - na_values: para reconocer valores faltantes específicos de este archivo
df = pd.read_csv(file_path, thousands=',', na_values=['-', ' -   ', '#DIV/0!', ' '])

In [47]:
df.describe()

,tara,tweight,dweight,pweight,chemical_id,%Fe,%Cu,%Zn,%Mo,%Ins,pSol
count,2622.000000,2622.000000,2622.000000,2622.000000,2.550000e+03,2605.000000,2605.000000,2513.000000,2605.000000,2450.000000,2627.000000
mean,109.958085,995.055988,215.209268,885.097941,9.127085e+08,418.901813,297.810334,2.203458,36.464258,82.171902,24.798135
std,2.496450,437.034748,122.408126,437.172970,9.277961e+08,3074.149211,2490.926202,61.964713,277.737536,1334.895500,13.768665
min,11.500000,174.500000,4.500000,60.000000,4.845000e+03,0.555000,0.010000,0.000000,0.000000,0.000000,0.680000
25%,109.000000,849.625000,117.500000,740.000000,5.817750e+03,3.219000,0.274000,0.000000,0.015000,0.000000,13.955000
50%,110.000000,977.000000,200.000000,867.750000,1.713198e+09,20.800000,11.101000,0.005000,0.438000,8.240000,24.380000
75%,110.500000,1101.375000,298.000000,991.375000,1.738942e+09,27.250000,21.113000,0.108000,1.151000,18.855000,34.890000
max,140.000000,13334.000000,1121.500000,13225.000000,1.750009e+10,30671.000000,29452.000000,1884.000000,6404.000000,38180.000000,295.000000